//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashminder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flashcard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flashcard()
        {
            this.Flashcard_Category = new HashSet<Flashcard_Category>();
        }
    
        public Nullable<int> UserId { get; set; }
        public int Id { get; set; }
        public string FrontText { get; set; }
        public string BackText { get; set; }
        public byte[] FrontImage { get; set; }
        public byte[] BackImage { get; set; }
        public int fk_CardType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual USERS USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flashcard_Category> Flashcard_Category { get; set; }
    }
}
