//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashminder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnection : DbContext
    {
        public DefaultConnection()
            : base("name=DefaultConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Flashcard_Category> Flashcard_Category { get; set; }
        public virtual DbSet<Flashcard> Flashcards { get; set; }
        public virtual DbSet<Flashcard_Algorithm_Data> Flashcard_Algorithm_Data { get; set; }
    }
}
