//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flashminder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flashcard_Algorithm_Data
    {
        public int Id { get; set; }
        public int FlashcardId { get; set; }
        public double Easiness { get; set; }
        public int Interval { get; set; }
        public byte Quality { get; set; }
        public System.DateTime NextPratice { get; set; }
        public int Repetitions { get; set; }
    
        public virtual Flashcard Flashcard { get; set; }
    }
}
